---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: test/integration
  modules_path: site
  hiera_data_path: hieradata
  hiera_data_remote_path: /etc/puppet/hieradata
  ignore_spec_fixtures: true
  custom_facts:
    packagecloud_master_token: <%= ENV['PACKAGECLOUD_MASTER_TOKEN'] %>

transport:
  name: sftp

platforms:
  - name: centos-7.2

suites:
  - name: profile-base
    provisioner:
      manifest: profile-base/init.pp
      custom_facts:
        puppet_role: base
  - name: profile-elasticsearch
    provisioner:
      manifest: profile-elasticsearch/init.pp
      custom_facts:
        puppet_role: elasticsearch
  - name: profile-nexus
    provisioner:
      manifest: profile-nexus/init.pp
      custom_facts:
        puppet_role: nexus
  - name: profile-mongodb
    provisioner:
      manifest: profile-mongodb/init.pp
      custom_facts:
        puppet_role: mongodb
