---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: site
  manifests_path: manifests
  manifest: site.pp
  hiera_data_path: hieradata
  hiera_data_remote_path: /etc/puppet/hieradata
  ignore_spec_fixtures: true
  custom_facts:
    packagecloud_master_token: <%= ENV['PACKAGECLOUD_MASTER_TOKEN'] %>
    master_password: randompassword

transport:
  name: sftp

platforms:
  - name: centos-7.2

suites:
  - name: profile-base
    provisioner:
      manifests_path: test/integration
      manifest: profile-base/init.pp
      custom_facts:
        puppet_role: base
  - name: profile-elasticsearch
    provisioner:
      manifests_path: test/integration
      manifest: profile-elasticsearch/init.pp
      custom_facts:
        puppet_role: elasticsearch
  - name: profile-nexus
    provisioner:
      manifests_path: test/integration
      manifest: profile-nexus/init.pp
      custom_facts:
        puppet_role: nexus
  - name: profile-mongodb
    provisioner:
      manifests_path: test/integration
      manifest: profile-mongodb/init.pp
      custom_facts:
        puppet_role: mongodb
