---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: site
  manifests_path: manifests
  manifest: site.pp
  hiera_data_path: hieradata
  hiera_data_remote_path: /etc/puppet/hieradata
  ignore_spec_fixtures: true
  puppet_environment: vagrant
  custom_facts:
    tic_db_host: localhost
    postgres_nodes: localhost
    packagecloud_master_token: <%= ENV['PACKAGECLOUD_MASTER_TOKEN'] %>
    master_password: mypassword

transport:
  name: sftp

platforms:
  - name: centos-7.2

verifier:
  name: serverspec
  remote_exec: false
  extra_flags: '--require spec_helper -I spec/acceptance'

suites:
  - name: role-frontend
    provisioner:
      custom_facts:
        puppet_role: frontend
    verifier:
      patterns:
        - 'spec/acceptance/frontend_spec.rb'
  - name: role-tic_services_internal
    provisioner:
      manifests_path: examples
      manifest: tic-services-internal.pp
      custom_facts:
        puppet_role: tic_services_internal
    verifier:
      patterns:
        - 'spec/acceptance/tic_services_internal_spec.rb'
  - name: role-tic_services_external
    provisioner:
      custom_facts:
        puppet_role: tic_services_external
    verifier:
      patterns:
        - 'spec/acceptance/tic_services_external_spec.rb'
  - name: role-activemq
    provisioner:
      custom_facts:
        puppet_role: activemq
    verifier:
      patterns:
        - 'spec/acceptance/activemq_spec.rb'
  - name: role-elasticsearch
    provisioner:
      custom_facts:
        puppet_role: elasticsearch
    verifier:
      patterns:
        - 'spec/acceptance/elasticsearch_spec.rb'
  - name: role-nexus
    provisioner:
      custom_facts:
        puppet_role: nexus
    verifier:
      patterns:
        - 'spec/acceptance/nexus_spec.rb'
  - name: role-syncope
    provisioner:
      custom_facts:
        puppet_role: syncope
    verifier:
      patterns:
        - 'spec/acceptance/syncope_spec.rb'
  - name: role-dataprep_dataset
    provisioner:
      custom_facts:
        puppet_role: dataprep_dataset
    verifier:
      patterns:
        - 'spec/acceptance/dataprep_dataset_spec.rb'
  - name: role-zookeeper
    provisioner:
      custom_facts:
        puppet_role: zookeeper
    verifier:
      patterns:
        - 'spec/acceptance/zookeeper_spec.rb'
  - name: profile-mongodb
    provisioner:
      manifests_path: examples
      manifest: profile-mongodb-init.pp
      custom_facts:
        puppet_role: mongodb
    verifier:
      patterns:
        - 'spec/acceptance/mongodb_spec.rb'
