HOSTS:
  centos-7-base:
    roles:
      - default
      - base
    vmname: centos-7-base
    platform: el-7-x86_64
    hypervisor: ec2
    amisize: t2.small
    snapshot: foss
    user: centos
CONFIG:
  type: foss
  log_level: verbose
  masterless: true
