fixtures:
  symlinks:
    role: '#{source_dir}'
    profile: '#{source_dir}/../profile'
  repositories:
    selinux: "git://github.com/jfryman/puppet-selinux.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    java: "git://github.com/puppetlabs/puppetlabs-java.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"