#HOSTS:
#  centos-7-x64:
#    platform: "el-7-x86_64"
#    box: "centos/7"
#    box_url: 'https://atlas.hashicorp.com/centos/boxes/7/versions/1603.01/providers/virtualbox.box'
#    hypervisor: vagrant
#CONFIG:
#  type: foss
#  log_level: verbose
#  masterless: true
#
HOSTS:
  centos-7:
    vmname: centos-7-us-east-1
    platform: el-7-x86_64
    hypervisor: ec2
    amisize: t2.small
    snapshot: foss
    user: centos
CONFIG:
  type: foss
  log_level: verbose
  masterless: true
